In [2]:
import pandas as pd

#q: how does deseq2 get p values?
#the Wald test

In [3]:
#load table from deseq2 and p values from permutation test
#disease Healthy vs AD
table_ad = pd.read_csv('../ad_res', sep = '\t', index_col = 0)
pvalues_ad = pd.read_csv('../ad_pvalues', sep = '\t', header=None)
# ++  Healthy higher 
# -- AD higher
#contrast=c("Groupings","Healthy","AD")



#disease Healthy vs CD
table_cd = pd.read_csv('../cd_res', sep = '\t', index_col = 0)
pvalues_cd = pd.read_csv('../cd_pvalues', sep = '\t', header=None)
# ++ healthy higher
# -- cd higher
#contrast=c("Groupings","Healthy","CD")


# disease UC vs Healthy
table_uc = pd.read_csv('../uc_res', sep = '\t', index_col = 0)
pvalues_uc = pd.read_csv('../uc_pvalues', sep = '\t', header=None)
# ++ higher uc
# -- higher healthy
# contrast=c("Groupings","Healthy","CD"), + higher healthy, - higher uc

#Example
#log2 fold change (MAP): dex trt vs untrt 
#contrast=c("condition","treated","untreated")
# log2FoldChange negative, untrt higher, 
# the denominator is 'untreated'

In [4]:
#add a new column called permutation_pvalues
table_ad['permutation_pvalues'] = pvalues_ad[0].values
table_cd['permutation_pvalues'] = pvalues_cd[0].values
table_uc['permutation_pvalues'] = pvalues_uc[0].values

In [311]:
all_kegg = pd.DataFrame(set(table_uc.index)|set(table_cd.index)|set(table_ad.index))
all_kegg.to_csv('all_kegg.txt', sep = '\t')

In [5]:
len(set(table_uc.index)|set(table_cd.index)|set(table_ad.index))

9090

In [6]:
#filter out keggs have permutation_pvalues > 0.05
table_ad_filtered = table_ad.loc[table_ad['permutation_pvalues'] <= 0.05]
table_ad_filtered = table_ad_filtered.dropna()
table_cd_filtered = table_cd.loc[table_cd['permutation_pvalues'] <= 0.05]
table_cd_filtered = table_cd_filtered.dropna()
table_uc_filtered = table_uc.loc[table_uc['permutation_pvalues'] <= 0.05]
table_uc_filtered = table_uc_filtered.dropna()

In [8]:
padj_ad = set(table_ad.loc[table_ad['padj'] < 0.05].index)
permutation_pvalues_ad = set(table_ad.loc[table_ad['permutation_pvalues'] < 0.05].index)
len(padj_ad&(permutation_pvalues_ad))

513

In [11]:
len(table_ad_filtered)*0.35

372.4

In [12]:
i = table_ad_filtered
i['CI_5'] = i['log2FoldChange'] - i['lfcSE']*1.96
i['CI_95'] = i['log2FoldChange'] + i['lfcSE']*1.96
#i_negative = i.sort_values(by=['CI_95'],ascending=True).head(444)
i_negative = i.sort_values(by=['CI_95'],ascending=True).head(372)

#i_positive = i.sort_values(by=['CI_5'],ascending=False).head(353)
i_positive = i.sort_values(by=['CI_5'],ascending=False).head(372)

ad_higher_in_case = set(i_negative.index)
ad_higher_in_control = set(i_positive.index)
# ++  Healthy higher 
# -- AD higher

In [13]:
len(table_cd_filtered)*0.35

1655.1499999999999

In [14]:
i = table_cd_filtered
i['CI_5'] = i['log2FoldChange'] - i['lfcSE']*1.96
i['CI_95'] = i['log2FoldChange'] + i['lfcSE']*1.96
#i_negative = i.sort_values(by=['CI_95'],ascending=True).head(2950)
i_negative = i.sort_values(by=['CI_95'],ascending=True).head(1655)

#i_positive = i.sort_values(by=['CI_5'],ascending=False).head(1349)
i_positive = i.sort_values(by=['CI_5'],ascending=False).head(1655)

cd_higher_in_case = set(i_negative.index)
cd_higher_in_control = set(i_positive.index)
# ++ healthy higher
# -- cd higher

In [15]:
len(table_uc_filtered)*0.35

632.8

In [16]:
i = table_uc_filtered
i['CI_5'] = i['log2FoldChange'] - i['lfcSE']*1.96
i['CI_95'] = i['log2FoldChange'] + i['lfcSE']*1.96
i_negative = i.sort_values(by=['CI_95'],ascending=True).head(633)
#i_negative = i.sort_values(by=['CI_95'],ascending=True).head(574)

#i_positive = i.sort_values(by=['CI_5'],ascending=False).head(911)
i_positive = i.sort_values(by=['CI_5'],ascending=False).head(633)

uc_higher_in_control = set(i_negative.index)
uc_higher_in_case = set(i_positive.index)

# ++ higher uc
# -- higher healthy

In [17]:
len(ad_higher_in_case.intersection(cd_higher_in_case))

8

In [18]:
len(ad_higher_in_control.intersection(cd_higher_in_control))

20

In [19]:
len(uc_higher_in_case.intersection(cd_higher_in_case))

309

In [20]:
len(uc_higher_in_control.intersection(cd_higher_in_control))

233

In [21]:
ad_higher_in_case.intersection(cd_higher_in_case) 
cd_ad_higher_in_case = pd.DataFrame(ad_higher_in_case.intersection(cd_higher_in_case))
cd_ad_higher_in_case.to_csv('cd_ad_higher_in_case.txt', sep = '\t')
ad_higher_in_control.intersection(cd_higher_in_control) 
cd_ad_higher_in_control = pd.DataFrame(ad_higher_in_control.intersection(cd_higher_in_control))
cd_ad_higher_in_control.to_csv('cd_ad_higher_in_control.txt', sep = '\t')

In [304]:
cd_uc_higher_in_case = pd.DataFrame(uc_higher_in_case.intersection(cd_higher_in_case))
cd_uc_higher_in_case.to_csv('cd_uc_higher_in_case.txt', sep = '\t')
cd_uc_higher_in_control = pd.DataFrame(uc_higher_in_control.intersection(cd_higher_in_control))
cd_uc_higher_in_control.to_csv('cd_uc_higher_in_control.txt', sep = '\t')

In [330]:
metadata_new = pd.read_table('../../Meta_diseases_analyses/table/eggNOG_species_rep.txt')

In [331]:
metadata_new

                                  Species    Species_rep
0               GCA-900066495 sp902362365  MGYG000000001
1                        Blautia_A faecis  MGYG000000002
2                        Alistipes shahii  MGYG000000003
3               Anaerotruncus colihominis  MGYG000000004
4           Terrisporobacter glycolicus_A  MGYG000000005
...                                   ...            ...
289227                 AM51-8 sp003478275  MGYG000000280
289228  Phascolarctobacterium sp000436095  MGYG000004337
289229                CAG-488 sp000434055  MGYG000000669
289230           Butyrivibrio_A crossotus  MGYG000001319
289231                    RC9 sp000431015  MGYG000000672

[289232 rows x 2 columns]

In [343]:
cd_ad_cases = list(cd_ad_higher_in_case[0])
len(cd_ad_cases)

28

In [ ]:
#map back to microbial species
#map genes back to species
genome_kegg_counts_n_ad = pd.read_csv('../../Meta_diseases_analyses/table/genome_kegg_counts_n_AD.txt', sep = '\t') 
genome_kegg_counts_n_ad = genome_kegg_counts_n_ad.set_index('Unnamed: 0')
a = list(cd_ad_higher_in_case[0])
df = genome_kegg_counts_n_ad.filter(a, axis=1)
#remove rows with all 0
df = df.loc[~(df==0).all(axis=1)]
# df_ad = pd.merge(df, metadata_new, how = "inner", left_index = True, right_on = 'Species_rep')
# df_ad_genus = df_ad.set_index('Genera')
# df_ad_genus = df_ad_genus.loc[:, 'ko:K01860':'ko:K11621']
# #df_ad_genus.to_csv('../table/df_ad_Tyrosine_bipartite_genera.txt', sep = '\t', index = True)
# df_ad = df_ad.set_index('Class')
# df_ad = df_ad.loc[:, 'ko:K01860':'ko:K11621']
# #df_ad.to_csv('../table/df_ad_Tyrosine_bipartite.txt', sep = '\t', index = True)

In [339]:
df

,ko:K01860,ko:K07106,ko:K16961,ko:K01628,ko:K01958,ko:K06990,ko:K10561,ko:K03646,ko:K06016,ko:K09930,ko:K00035,ko:K08688,ko:K03502,ko:K01524,ko:K19002,ko:K02241,ko:K19428,ko:K13797,ko:K10238,ko:K11621
Unnamed: 0,,,,,,,,,,,,,,,,,,,,
MGYG000003731,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
MGYG000001658,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,0,0
MGYG000004593,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0
MGYG000002152,0,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
MGYG000001462,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MGYG000004108,0,1,0,1,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0
MGYG000002737,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
MGYG000002589,0,1,0,0,0,0,0,0,0,0,0,0,2,0,2,0,0,0,0,0
MGYG000000690,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0
MGYG000002601,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

In [341]:
df

,ko:K01860,ko:K07106,ko:K16961,ko:K01628,ko:K01958,ko:K06990,ko:K10561,ko:K03646,ko:K06016,ko:K09930,ko:K00035,ko:K08688,ko:K03502,ko:K01524,ko:K19002,ko:K02241,ko:K19428,ko:K13797,ko:K10238,ko:K11621
Unnamed: 0,,,,,,,,,,,,,,,,,,,,
MGYG000001658,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,0,0,0,0,0
MGYG000004593,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0
MGYG000002152,0,1,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0
MGYG000001462,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0
MGYG000003489,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MGYG000004108,0,1,0,1,0,0,0,0,0,0,0,0,2,1,0,0,0,0,0,0
MGYG000002737,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
MGYG000002589,0,1,0,0,0,0,0,0,0,0,0,0,2,0,2,0,0,0,0,0
MGYG000000690,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0
MGYG000002601,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0